### ISSUE TITLE
Some datasets are missing?

### ISSUE THREAD

**Issue by sancarn** [marlersoft/win32json#3]
This might be a known issue already, but I think `WinUser` is missing. I also couldn't find functions from `Kernel32` (although i don't know what this file would be called either). E.G. I can't find functions like `SendMessageA` and `SetWindowHookEx`

**Comment by marler8997** [comment]
Here's `SendMessageA`: https://github.com/marlersoft/win32json/blob/38584ea6687bcda47570b866b4fd6cfe24361187/api/UI.WindowsAndMessaging.json#L15144-L15159

It looks like SetWindowsHook:Ex is missing, I'll open an issue in the metadata repo for that: https://github.com/microsoft/win32metadata/issues/685

**Comment by marler8997** [comment]
Oh it looks like the problem was a typo.  It's `SetWindowsHookExA`, not `SetWindowHookEx`:

https://github.com/marlersoft/win32json/blob/38584ea6687bcda47570b866b4fd6cfe24361187/api/UI.WindowsAndMessaging.json#L19257-L19270

**Comment by sancarn** [comment]
Oh you're right ;-; Apologies! haha
